"""Shared pytest fixtures for mo2-assets-engine tests."""

from __future__ import annotations

import struct
from pathlib import Path

import pytest


@pytest.fixture()
def sample_profile_dir(tmp_path: Path) -> Path:
    """Synthetic MO2 profile with 3 enabled mods + 1 disabled + 1 separator."""

    profile = tmp_path / "profiles" / "Default"
    profile.mkdir(parents=True)

    # MO2 lists mods top-to-bottom from LAST applied (top wins).
    # Order top-to-bottom: ModC (prio 2), EnabledSep_separator (skipped),
    # ModB (prio 1), DisabledSep_separator (skipped), ModA (prio 0),
    # DisabledMod (skipped). Real MO2 uses `+`/`-` prefix for separators
    # with a `_separator` name suffix, NOT `*` prefix — that was an old
    # mis-documented convention.
    (profile / "modlist.txt").write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "+ModC\n"
        "+EnabledSep_separator\n"
        "+ModB\n"
        "-DisabledSep_separator\n"
        "+ModA\n"
        "-DisabledMod\n",
        encoding="utf-8",
    )

    # BGS asterisk-prefix format: `*` = enabled, leading `*` only for
    # non-official masters. For test purposes, two enabled plugins.
    (profile / "plugins.txt").write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "*ModB.esp\n"
        "*ModA.esp\n",
        encoding="utf-8",
    )

    mods_root = tmp_path / "mods"
    for name in ("ModA", "ModB", "ModC", "DisabledMod"):
        (mods_root / name).mkdir(parents=True)

    return profile


def _ba2_pad_name(name: str) -> bytes:
    encoded = name.encode("utf-8")
    return struct.pack("<H", len(encoded)) + encoded


@pytest.fixture()
def synthetic_ba2_gnrl(tmp_path: Path) -> Path:
    """Build a minimal valid BA2 v1 GNRL archive with 3 known members.

    Layout: header (24 bytes) + 3 x (36-byte entry record) + 3 file payloads
    (uncompressed) + name table. Member names match what a real FO4 BA2
    would contain.
    """
    archive_path = tmp_path / "TestPack - Main.ba2"
    members = [
        ("materials/test/foo.bgsm", b"FOO-BGSM-PAYLOAD"),
        ("scripts/source/user/test.psc", b"PAYLOAD-2"),
        ("strings/test_en.strings", b"PAYLOAD-3"),
    ]
    file_count = len(members)
    header_size = 24
    entry_size = 36

    name_offsets_start = header_size + entry_size * file_count
    payloads_offset = name_offsets_start
    file_records = []
    cursor = payloads_offset
    for _name, payload in members:
        file_records.append((cursor, len(payload)))
        cursor += len(payload)
    name_table_offset = cursor

    out = bytearray()
    # Header: magic "BTDX", version 1, type "GNRL", file_count, name_table_offset
    out += struct.pack("<4sI4sIQ", b"BTDX", 1, b"GNRL", file_count, name_table_offset)
    # Entry records (36 bytes each).
    for (_name, _payload), (offset, size) in zip(members, file_records, strict=True):
        out += struct.pack(
            "<IIIIQIII",
            0,            # name_hash
            0,            # ext
            0,            # dir_hash
            0,            # unknown
            offset,
            0,            # packed_size = 0 -> uncompressed
            size,
            0xBAADF00D,   # sentinel
        )
    for _name, payload in members:
        out += payload
    for name, _payload in members:
        out += _ba2_pad_name(name)

    archive_path.write_bytes(bytes(out))
    return archive_path


@pytest.fixture()
def synthetic_ba2_dx10(tmp_path: Path) -> Path:
    """Build a minimal valid BA2 v1 DX10 archive with 2 known texture members.

    Layout: header (24 bytes) + per-file (texture header 24 bytes +
    1 chunk header 24 bytes) + payloads + name table.
    """
    archive_path = tmp_path / "TestTextures - Textures.ba2"
    members = [
        ("textures/test/foo.dds", b"DDS-PAYLOAD-1"),
        ("textures/test/bar.dds", b"DDS-PAYLOAD-2"),
    ]
    file_count = len(members)
    header_size = 24
    per_file_record_size = 24 + 24 * 1  # tex header + 1 chunk header
    name_offsets_start = header_size + per_file_record_size * file_count
    payloads_offset = name_offsets_start
    file_records = []
    cursor = payloads_offset
    for _name, payload in members:
        file_records.append((cursor, len(payload)))
        cursor += len(payload)
    name_table_offset = cursor

    out = bytearray()
    out += struct.pack("<4sI4sIQ", b"BTDX", 1, b"DX10", file_count, name_table_offset)
    for (_name, _payload), (offset, size) in zip(members, file_records, strict=True):
        # Texture header (24 bytes).
        out += struct.pack(
            "<IIIBBHHHBBBB",
            0,      # name_hash
            0,      # ext
            0,      # dir_hash
            0,      # unk8
            1,      # num_chunks
            24,     # chunk_header_size
            1024,   # height
            1024,   # width
            1,      # num_mips
            87,     # format (BC7_UNORM)
            0,      # is_cubemap
            8,      # tile_mode
        )
        # Chunk header (24 bytes).
        out += struct.pack(
            "<QIIHHI",
            offset,
            0,                # packed_size = 0 -> uncompressed
            size,
            0,                # start_mip
            0,                # end_mip
            0xBAADF00D,
        )
    for _name, payload in members:
        out += payload
    for name, _payload in members:
        out += _ba2_pad_name(name)

    archive_path.write_bytes(bytes(out))
    return archive_path


@pytest.fixture()
def synthetic_bsa_v105(tmp_path: Path) -> Path:
    """Build a minimal valid BSA v105 archive with 2 folders + 4 files.

    No real payload bytes — file offsets/sizes are placeholders because the
    reader only walks the directory structure for filename enumeration.

    Per the UESP spec, v105 file-record `offset` is stored as
    `folder_offset + total_file_name_length`; the reader subtracts
    `total_file_name_length` to recover the position of the per-folder
    name+records block.
    """
    archive_path = tmp_path / "TestPack.bsa"
    folders = [
        ("textures/test", ["foo.dds", "bar.dds"]),
        ("meshes/test", ["foo.nif", "bar.nif"]),
    ]

    archive_flags = 0b11  # folder names + file names included
    folder_record_size = 24  # v105

    folder_count = len(folders)
    file_count = sum(len(files) for _, files in folders)
    total_folder_name_length = sum(len(name) + 1 for name, _ in folders)  # incl null
    total_file_name_length = sum(
        len(fname) + 1 for _, fnames in folders for fname in fnames
    )

    out = bytearray()
    # Header (36 bytes).
    out += struct.pack(
        "<4sIIIIIIII",
        b"BSA\x00",
        105,
        36,                          # folder_offset (= header size)
        archive_flags,
        folder_count,
        file_count,
        total_folder_name_length,
        total_file_name_length,
        0,                           # file_flags (unused for enumeration)
    )

    folder_records_block_size = folder_record_size * folder_count
    cursor = 36 + folder_records_block_size
    folder_offsets: list[int] = []
    for folder_name, fnames in folders:
        folder_offsets.append(cursor)
        # 1 byte length + folder_name + null + file_count * 16
        cursor += 1 + len(folder_name) + 1 + len(fnames) * 16

    # Folder records (24 bytes each).
    for (_folder_name, fnames), folder_offset in zip(folders, folder_offsets, strict=True):
        out += struct.pack(
            "<QIIQ",
            0,                # name_hash (unused)
            len(fnames),      # file_count
            0,                # v105 padding
            folder_offset + total_file_name_length,
        )

    # Per-folder name block + file records.
    for folder_name, fnames in folders:
        out += bytes([len(folder_name) + 1])
        out += folder_name.encode("ascii") + b"\x00"
        for fname in fnames:
            out += struct.pack(
                "<QII",
                0,            # name_hash
                len(fname),   # size_and_flags
                0,            # offset
            )

    # File names block: null-terminated names, in file-record order across folders.
    for _folder, fnames in folders:
        for fname in fnames:
            out += fname.encode("ascii") + b"\x00"

    archive_path.write_bytes(bytes(out))
    return archive_path
