import { describe, it, expect, beforeAll } from "vitest";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { getTool, _clearToolsForTests } from "../../src/tool-registry.js";
import { PlanCache } from "../../src/plan-apply.js";
import { SnapshotManager } from "../../src/snapshot.js";
import { AuditLogger } from "../../src/audit.js";
import type { ToolContext } from "../../src/types.js";

async function _buildCtx(): Promise<ToolContext> {
  const root = await mkdtemp(join(tmpdir(), "mo2-pl-"));
  await mkdir(join(root, "profiles", "Default"), { recursive: true });
  await writeFile(join(root, "profiles", "Default", "modlist.txt"), "", "utf8");
  await writeFile(
    join(root, "profiles", "Default", "plugins.txt"),
    "# This file was automatically generated by Mod Organizer.\n*Fallout4.esm\n*DLCRobot.esm\nDisabled.esp\n# comment line\n",
    "utf8",
  );
  return {
    config: {
      mo2Root: root,
      permissionCeiling: "metadata-editable",
      allowedProfiles: ["Default"],
      deny: [],
      snapshotRoot: join(root, ".mo2-mcp", "snapshots"),
      auditRoot: join(root, ".mo2-mcp", "audit"),
    },
    sessionId: "test",
    plans: new PlanCache(),
    snapshots: new SnapshotManager(join(root, ".mo2-mcp", "snapshots"), "test"),
    audit: new AuditLogger(join(root, ".mo2-mcp", "audit"), "test"),
  };
}

describe("mo2_pluginlist", () => {
  beforeAll(async () => {
    _clearToolsForTests();
    await import("../../src/tools/mo2-pluginlist.js");
  });

  it("registers as T1", () => {
    const tool = getTool("mo2_pluginlist");
    expect(tool).toBeDefined();
    expect(tool!.tier).toBe("T1");
  });

  it("returns plugins with correct * polarity (* = enabled)", async () => {
    const ctx = await _buildCtx();
    const tool = getTool("mo2_pluginlist")!;
    const result = (await tool.handler({}, ctx)) as {
      ok: boolean;
      result: { plugins: Array<{ name: string; enabled: boolean; isComment?: boolean }> };
    };
    expect(result.ok).toBe(true);
    const plugins = result.result.plugins;
    expect(plugins).toHaveLength(5);
    expect(plugins[0]).toMatchObject({ name: "This file was automatically generated by Mod Organizer.", enabled: false, isComment: true });
    expect(plugins[1]).toMatchObject({ name: "Fallout4.esm", enabled: true });
    expect(plugins[3]).toMatchObject({ name: "Disabled.esp", enabled: false });
    expect(plugins[4]).toMatchObject({ name: "comment line", enabled: false, isComment: true });
  });

  it("assigns gui_rank and load_order_role only to real plugin entries", async () => {
    const ctx = await _buildCtx();
    const tool = getTool("mo2_pluginlist")!;
    const result = (await tool.handler({}, ctx)) as {
      result: { plugins: Array<{ name: string; isComment?: boolean; gui_rank?: number; load_order_role?: string }> };
    };
    const plugins = result.result.plugins;

    expect(plugins[0]).toMatchObject({ isComment: true });
    expect(plugins[0]).not.toHaveProperty("gui_rank");
    expect(plugins[0]).not.toHaveProperty("load_order_role");
    expect(plugins[1]).toMatchObject({ name: "Fallout4.esm", gui_rank: 1, load_order_role: "loads_first_lowest_precedence" });
    expect(plugins[2]).toMatchObject({ name: "DLCRobot.esm", gui_rank: 2, load_order_role: "intermediate" });
    expect(plugins[3]).toMatchObject({ name: "Disabled.esp", gui_rank: 3, load_order_role: "loads_last_highest_precedence" });
    expect(plugins[4]).toMatchObject({ isComment: true });
    expect(plugins[4]).not.toHaveProperty("gui_rank");
  });

  it("uses broker priority for gui_rank when enriched", async () => {
    const ctx = (await _buildCtx()) as ToolContext & { pipeClient: { call: (method: string) => Promise<unknown> } };
    ctx.pipeClient = {
      call: async (method: string) => {
        expect(method).toBe("plugins.list");
        return {
          ok: true,
          result: {
            plugins: [
              { name: "Fallout4.esm", priority: 2, load_order: 0 },
              { name: "DLCRobot.esm", priority: 0, load_order: 1 },
              { name: "Disabled.esp", priority: 1, load_order: 2 },
            ],
          },
        };
      },
    };
    const tool = getTool("mo2_pluginlist")!;
    const result = (await tool.handler({ enrich: true }, ctx)) as {
      result: { plugins: Array<{ name: string; isComment?: boolean; priority?: number; gui_rank?: number }> };
    };
    const byName = new Map(result.result.plugins.filter((p) => !p.isComment).map((p) => [p.name, p]));

    expect(byName.get("DLCRobot.esm")).toMatchObject({ priority: 0, gui_rank: 1 });
    expect(byName.get("Disabled.esp")).toMatchObject({ priority: 1, gui_rank: 2 });
    expect(byName.get("Fallout4.esm")).toMatchObject({ priority: 2, gui_rank: 3 });
  });

  it("documents GUI-aligned plugin array semantics in _meta", async () => {
    const ctx = await _buildCtx();
    const tool = getTool("mo2_pluginlist")!;
    const result = (await tool.handler({}, ctx)) as {
      result: { _meta: { array_order: string; array_order_note: string; enabled_marker: string } };
    };

    expect(result.result._meta.array_order).toBe("plugins_txt_forward_order_matches_gui");
    expect(result.result._meta.array_order_note).toContain("TOP of MO2 GUI plugins panel");
    expect(result.result._meta.enabled_marker).toContain("plugin_count includes the comment header entry");
  });
});
