"""Shared pytest fixtures for mo2-assets-engine tests."""

from __future__ import annotations

from pathlib import Path

import pytest


@pytest.fixture()
def sample_profile_dir(tmp_path: Path) -> Path:
    """Synthetic MO2 profile with 3 enabled mods + 1 disabled + 1 separator."""

    profile = tmp_path / "profiles" / "Default"
    profile.mkdir(parents=True)

    # MO2 lists mods top-to-bottom from LAST applied (top wins).
    # Order top-to-bottom: ModC (prio 2), Separator, ModB (prio 1),
    # ModA (prio 0), DisabledMod (not counted).
    (profile / "modlist.txt").write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "+ModC\n"
        "*Separator_separator\n"
        "+ModB\n"
        "+ModA\n"
        "-DisabledMod\n",
        encoding="utf-8",
    )

    # BGS asterisk-prefix format: `*` = enabled, leading `*` only for
    # non-official masters. For test purposes, two enabled plugins.
    (profile / "plugins.txt").write_text(
        "# This file was automatically generated by Mod Organizer.\n"
        "*ModB.esp\n"
        "*ModA.esp\n",
        encoding="utf-8",
    )

    mods_root = tmp_path / "mods"
    for name in ("ModA", "ModB", "ModC", "DisabledMod"):
        (mods_root / name).mkdir(parents=True)

    return profile
