# ruff: noqa: RUF001
"""Human-readable BGS record signature explanations for prompt context."""

from __future__ import annotations

from collections.abc import Iterable

SIGNATURE_EXPLANATIONS: dict[str, str] = {
    "TES4": "插件文件头/主记录信息，通常是插件名、作者、描述等元数据。",
    "GMST": "游戏设置值，通常是引擎或玩法参数的名字或说明。",
    "GLOB": "全局变量，通常是脚本/任务中引用的数值变量，不要改写变量名。",
    "KYWD": "关键词，用于给物品、地点、任务等打标签；名称要短，常作为分类或条件。",
    "LCRT": "地点引用类型，用于标记地点中的特殊引用点。",
    "AACT": "动作类型，通常是动画/行为相关标签。",
    "TXST": "材质集，通常不含玩家可见文本。",
    "MICN": "菜单图标/图标资源，通常不含玩家可见文本。",
    "GDRY": "God ray/渲染相关资源，通常不含玩家可见文本。",
    "CLAS": "角色职业/类别，可包含职业名称或说明。",
    "FACT": "阵营/组织，可包含组织名称、等级名称、说明。",
    "HDPT": "头部部件/角色外观部件。",
    "HAIR": "发型资源，可包含发型名称。",
    "EYES": "眼睛资源，可包含眼睛名称。",
    "RACE": "种族/物种，可包含种族名称、描述和能力说明。",
    "SOUN": "声音描述符，通常不含玩家可见文本。",
    "ASPC": "声学空间，通常不含玩家可见文本。",
    "MGEF": "魔法/能力/效果，可包含效果名称、描述、条件说明。",
    "SCPT": "脚本记录，通常不直接翻译脚本标识符。",
    "LTEX": "地表材质，可包含材质名称。",
    "ENCH": "附魔/强化效果，可包含效果名称或描述。",
    "SPEL": "法术/能力，可包含名称、描述、效果文本。",
    "SCRL": "卷轴，可包含名称和描述。",
    "ACTI": "可激活物体，例如按钮、门铃、终端互动对象的名称。",
    "TACT": "会说话的可激活物体，例如对话终端/广播对象。",
    "ARMO": "护甲/服装，可包含装备名称、描述、附加说明。",
    "BOOK": "书籍/纸条/数据板，可包含标题、正文、描述。",
    "CONT": "容器，可包含箱子、储物柜、尸体容器等名称。",
    "DOOR": "门/传送门，可包含门名、地点入口名。",
    "INGR": "材料/炼金原料，可包含名称和效果说明。",
    "LIGH": "光源物体，可包含可见名称。",
    "MISC": "杂项物品，可包含道具名称、说明、任务物品名称。",
    "APPA": "炼金器具/工具。",
    "STAT": "静态物体，通常不含玩家可见文本。",
    "SCOL": "静态集合，通常不含玩家可见文本。",
    "MSTT": "可移动静态物体，通常不含玩家可见文本。",
    "PWAT": "水面/放置水资源，通常不含玩家可见文本。",
    "GRAS": "草/植被资源，通常不含玩家可见文本。",
    "TREE": "树木资源，通常不含玩家可见文本。",
    "FLOR": "植物/可采集 flora，可包含植物名称和采集提示。",
    "FURN": "家具/可使用装置，可包含互动名称。",
    "WEAP": "武器，可包含武器名称、描述、模组化附件名。",
    "AMMO": "弹药，可包含弹药名称。",
    "NPC_": "NPC/角色，可包含角色名、称号、模板名。",
    "LVLN": "NPC 等级列表，通常不直接显示给玩家。",
    "LVLI": "物品等级列表，通常不直接显示给玩家。",
    "KEYM": "钥匙/门禁物品，可包含钥匙名称。",
    "ALCH": "药剂/食物/化学品，可包含名称、描述、效果文本。",
    "IDLM": "待机动画标记，通常不含玩家可见文本。",
    "NOTE": "笔记/音频记录/数据记录，可包含标题和正文。",
    "COBJ": "制作配方，可包含配方名或制作条件文本。",
    "PROJ": "弹射物，通常不含玩家可见文本。",
    "HAZD": "危险区域/持续伤害对象，通常不含玩家可见文本。",
    "SLGM": "灵魂石/能量容器，可包含物品名称。",
    "TERM": "终端/电脑，可包含终端标题、菜单项、页面文本。",
    "LVSP": "法术等级列表，通常不直接显示给玩家。",
    "WTHR": "天气，可包含天气名称。",
    "CLMT": "气候，可包含区域气候名称。",
    "SPGD": "着色器粒子几何，通常不含玩家可见文本。",
    "RFCT": "视觉效果，通常不含玩家可见文本。",
    "REGN": "区域，可包含区域名称或天气/音效区域说明。",
    "NAVI": "导航网格信息，通常不含玩家可见文本。",
    "CELL": "室内/室外单元格，可包含地点名称。",
    "WRLD": "世界空间，可包含世界/地图区域名称。",
    "DIAL": "对话主题/话题，常对应玩家看到的对话选项或话题名。",
    "INFO": "对话信息/回复文本，常是 NPC 台词、玩家回复或对话条件文本。",
    "QUST": "任务，可包含任务名、目标、阶段说明、任务日志、提示文本。",
    "IDLE": "动画/行为空闲记录，通常不含玩家可见文本。",
    "PACK": "AI 包/行为包，可包含调试或行为名称，通常少量显示。",
    "CSTY": "战斗风格，通常不含玩家可见文本。",
    "LSCR": "加载界面，可包含加载提示文字。",
    "LVLC": "生物等级列表，通常不直接显示给玩家。",
    "ANIO": "动画对象，通常不含玩家可见文本。",
    "WATR": "水体，可包含水体名称。",
    "EFSH": "效果着色器，通常不含玩家可见文本。",
    "EXPL": "爆炸效果，通常不含玩家可见文本。",
    "DEBR": "碎片资源，通常不含玩家可见文本。",
    "IMGS": "图像空间，通常不含玩家可见文本。",
    "IMAD": "图像空间适配器，通常不含玩家可见文本。",
    "FLST": "表单列表，通常不直接显示给玩家。",
    "PERK": "Perk/技能特性，可包含名称、等级说明、效果描述。",
    "BPTD": "身体部位数据，通常不含玩家可见文本。",
    "ADDN": "附加节点/装饰对象，通常不含玩家可见文本。",
    "AVIF": "Actor Value/属性值，可包含技能、状态、属性名称和描述。",
    "CAMS": "摄像机镜头，通常不含玩家可见文本。",
    "CPTH": "相机路径，通常不含玩家可见文本。",
    "VTYP": "语音类型，通常是角色语音分类名。",
    "MATT": "材质类型，通常不含玩家可见文本。",
    "IPCT": "冲击数据，通常不含玩家可见文本。",
    "IPDS": "冲击数据集，通常不含玩家可见文本。",
    "ARMA": "护甲附加模型，通常不含玩家可见文本。",
    "ECZN": "遭遇区域，可包含区域名称。",
    "LCTN": "地点/location，可包含地图地点名、地点说明、父子地点关系。",
    "MESG": "消息框/通知，可包含弹窗、确认框、HUD 提示或系统消息。",
    "RGDL": "布娃娃/物理数据，通常不含玩家可见文本。",
    "DOBJ": "默认对象管理器，通常不含玩家可见文本。",
    "DFOB": "默认对象，通常不含玩家可见文本。",
    "LGTM": "光照模板，通常不含玩家可见文本。",
    "MUSC": "音乐类型，可包含音乐分类名。",
    "FSTP": "脚步类型，通常不含玩家可见文本。",
    "FSTS": "脚步集，通常不含玩家可见文本。",
    "SMBN": "故事管理分支节点，通常不直接显示给玩家。",
    "SMQN": "故事管理任务节点，通常不直接显示给玩家。",
    "SMEN": "故事管理事件节点，通常不直接显示给玩家。",
    "DLBR": "对话分支，可包含话题/分支名称。",
    "MUST": "音乐轨道，通常不含玩家可见文本。",
    "DLVW": "对话视图，通常不直接显示给玩家。",
    "WOOP": "龙吼/特殊能力词，可包含名称与说明。",
    "SHOU": "龙吼/特殊能力，可包含名称与说明。",
    "EQUP": "装备类型，可包含分类名称。",
    "RELA": "关系数据，通常不直接显示给玩家。",
    "SCEN": "场景，可包含场景名、对白组织结构。",
    "ASTP": "关联类型，可包含关系/关联名称。",
    "OTFT": "外观/装备模板，通常不直接显示给玩家。",
    "ARTO": "美术对象，通常不含玩家可见文本。",
    "MATO": "材质对象，通常不含玩家可见文本。",
    "MOVT": "移动类型，通常不含玩家可见文本。",
    "SNDR": "声音记录，通常不含玩家可见文本。",
    "DUAL": "双重施法数据，通常不含玩家可见文本。",
    "SNCT": "声音类别，可包含设置菜单里的声音分类名。",
    "SOPM": "声音输出模型，通常不含玩家可见文本。",
    "COLL": "碰撞层，通常不含玩家可见文本。",
    "CLFM": "颜色表单，通常可包含颜色名称。",
    "REVB": "混响参数，通常不含玩家可见文本。",
    "LENS": "镜头光晕，通常不含玩家可见文本。",
    "VOLI": "体积光照，通常不含玩家可见文本。",
    "OMOD": "物品/武器/护甲改造模块，可包含改件名称、描述和属性说明。",
    "INNR": "实例命名规则，可影响物品组合名称。",
    "KSSM": "声音关键词映射，通常不含玩家可见文本。",
    "AORU": "吸引/排斥规则，通常不含玩家可见文本。",
    "SCCO": "场景集合，通常不含玩家可见文本。",
    "AOPS": "动画对象/姿态资源，通常不含玩家可见文本。",
    "PKIN": "包裹实例/物品组合，可包含名称。",
    "RFGP": "引用组，通常不含玩家可见文本。",
    "AMDL": "瞄准模型，通常不含玩家可见文本。",
    "LAYR": "图层，通常不含玩家可见文本。",
    "ZOOM": "瞄准镜缩放数据，通常不含玩家可见文本。",
    "SCSN": "音效场景，通常不含玩家可见文本。",
    "GBFM": "Starfield 地面/星球/宇宙相关表单，可包含地点、目标或界面文本。",
    "TMLM": "Starfield 时间线/任务相关数据，可包含任务或地点提示。",
    "IRES": "Starfield 实例化资源/研究相关数据，可包含研究或制造名称。",
}

DETAILED_SIGNATURE_EXPLANATIONS: dict[str, str] = {
    "TES4": "Meaning this entry is from the plugin file header record. It usually describes the plugin itself, such as the mod title, author notes, masters, or metadata; translate only player-visible descriptive text and preserve technical identifiers.",
    "GMST": "Meaning this entry is from a Game Setting record. It usually stores engine or gameplay setting text; translate player-facing labels or descriptions, but do not alter setting keys or numeric-looking values.",
    "GLOB": "Meaning this entry is from a Global Variable record. It usually represents a numeric variable used by quests, scripts, or conditions; preserve variable-like names and translate only genuinely player-visible text.",
    "DOBJ": "Meaning this entry is from a Default Object Manager record. It maps engine defaults and is usually technical; translate only if the source is clearly player-facing.",
    "FLST": "Meaning this entry is from a FormID List record. It is usually a technical list of forms; translate only player-facing list names if present.",
    "DIAL": "Meaning this entry is from a Dialogue Topic record. It usually represents a conversation topic or player dialogue option; translate naturally as spoken or menu dialogue, and use nearby INFO/QUST context when available.",
    "INFO": "Meaning this entry is from a Dialogue Response/Info record. It usually contains NPC lines, player replies, or dialogue condition text; translate as natural speech while preserving placeholders and speaker intent.",
    "QUST": "Meaning this entry is from a Quest record. It usually contains quest titles, objectives, stage logs, mission board text, or quest targets; keep objectives concise and consistent with game UI terminology.",
    "MESG": "Meaning this entry is from a Message record. It usually appears as a popup, notification, confirmation prompt, or HUD message; translate clearly and briefly for in-game UI.",
    "BOOK": "Meaning this entry is from a Book, note, data slate, terminal page, or readable document record. It may contain a title, description, or long body text; preserve formatting and translate prose in the intended voice.",
    "LSCR": "Meaning this entry is from a Loading Screen record. It usually contains loading tips or lore snippets; translate as concise player-facing help or lore text.",
    "NPC_": "Meaning this entry is from an NPC base record. It usually contains a character name, title, or template label; preserve proper names unless a known official Chinese translation exists.",
    "RACE": "Meaning this entry is from a Race or species record. It usually contains race/species names, descriptions, or ability text; preserve lore terms consistently.",
    "CLAS": "Meaning this entry is from a Class record. It usually describes an NPC class, archetype, or role; translate as a compact role label unless the field is a longer description.",
    "FACT": "Meaning this entry is from a Faction record. It usually contains faction names, rank names, organization labels, or reputation text; preserve official faction terminology.",
    "PACK": "Meaning this entry is from an AI Package record. It usually describes behavior packages and may be technical; translate only player-visible labels if they appear.",
    "PERK": "Meaning this entry is from a Perk or character trait record. It usually contains perk names, ranks, and effect descriptions; translate as gameplay UI text and keep numeric/stat placeholders exact.",
    "AVIF": "Meaning this entry is from an Actor Value record. It usually represents a skill, attribute, resistance, or status value; translate as a short gameplay stat label.",
    "CSTY": "Meaning this entry is from a Combat Style record. It is usually technical AI data; translate only if the text is player-facing.",
    "VTYP": "Meaning this entry is from a Voice Type record. It usually labels a voice category or actor voice; preserve names and translate only descriptive labels.",
    "ACHR": "Meaning this entry is from a placed Actor reference. It usually identifies a placed NPC in the world; translate only player-visible names, not reference identifiers.",
    "PLYR": "Meaning this entry is from the Player reference record. It is usually technical; preserve identifiers and translate only visible text.",
    "WEAP": "Meaning this entry is from a Weapon record. It usually contains a weapon name, weapon description, ammo-related label, or weapon part name; translate as an item name while preserving model names, calibers, and placeholders.",
    "ARMO": "Meaning this entry is from an Armor or clothing record. It usually contains wearable item names, outfit names, or armor descriptions; keep names concise and consistent with equipment UI.",
    "ARMA": "Meaning this entry is from an Armor Addon record. It usually describes the model/visual attachment behind an armor item and is often technical; translate only visible labels.",
    "ALCH": "Meaning this entry is from an ingestible item record, such as food, drink, medicine, chem, potion, or consumable. Translate as an item name or effect description and preserve dosage/effect tokens.",
    "AMMO": "Meaning this entry is from an Ammunition record. It usually contains ammo names or ammo type labels; preserve calibers, units, and model codes.",
    "INGR": "Meaning this entry is from an Ingredient record. It usually contains ingredient names or effect text; translate as material/food/chemical item names.",
    "KEYM": "Meaning this entry is from a Key record. It usually contains key, keycard, pass, or access item names; translate as a short inventory item label.",
    "MISC": "Meaning this entry is from a Miscellaneous Item record. It usually contains loot, quest items, crafting components, clutter item names, or descriptions; translate as inventory text.",
    "COBJ": "Meaning this entry is from a Constructible Object or crafting recipe record. It usually contains recipe names, workshop/building labels, or crafting menu text; translate as crafting UI text.",
    "ENCH": "Meaning this entry is from an Enchantment/Object Effect record. It usually contains effect names or descriptions attached to items; translate as gameplay effect text.",
    "SPEL": "Meaning this entry is from a Spell, ability, power, or effect record. It usually contains ability names and descriptions; translate as gameplay ability UI text.",
    "ACTI": "Meaning this entry is from an Activator record, used in the game to activate something, usually a button, switch, prop, marker, or interactive object. Translate short interaction labels naturally.",
    "TACT": "Meaning this entry is from a Talking Activator record. It is an activator that can speak or trigger dialogue/audio; translate labels or dialogue-facing text as interaction or speech context.",
    "DOOR": "Meaning this entry is from a Door record. It usually contains door names, destination labels, or entrance names; translate as a location/interaction label.",
    "CONT": "Meaning this entry is from a Container record. It usually contains container names such as crates, lockers, corpses, or storage objects; translate as a short in-world object label.",
    "FURN": "Meaning this entry is from a Furniture record. It usually represents a usable chair, bed, crafting station, terminal seat, or interaction point; translate the interaction/object label.",
    "LIGH": "Meaning this entry is from a Light record. It usually represents a light object and is often technical; translate only visible object names if present.",
    "STAT": "Meaning this entry is from a Static object record. It usually represents non-interactive world geometry or props and is often technical; translate only if clearly shown to players.",
    "MSTT": "Meaning this entry is from a Movable Static record. It usually represents movable world props and is often technical; translate only visible names.",
    "SCOL": "Meaning this entry is from a Static Collection record. It usually groups static objects and is technical; translate only visible labels.",
    "SOUN": "Meaning this entry is from a Sound Marker or Sound record. It is usually technical audio data; translate only user-visible labels.",
    "REGN": "Meaning this entry is from a Region record. It may name a world region or define weather/audio behavior; translate region names as location terms.",
    "WTHR": "Meaning this entry is from a Weather record. It may contain a weather name or climate-facing label; translate as environmental terminology.",
    "WATR": "Meaning this entry is from a Water record. It may contain a water type name; translate only visible names.",
    "CELL": "Meaning this entry is from a Cell record, representing an interior or exterior world cell. It often contains location names shown on doors, maps, or loading screens; translate as a place name.",
    "WRLD": "Meaning this entry is from a Worldspace record. It usually names a large world, planet surface, map, or exterior space; translate as a major location name.",
    "REFR": "Meaning this entry is from a placed Object Reference. It identifies a placed object in the world; translate only player-visible reference names, not technical IDs.",
    "NAVM": "Meaning this entry is from a Navigation Mesh record. It is usually technical AI navigation data; translate only visible labels if any.",
    "NAVI": "Meaning this entry is from Navigation Mesh Info Map data. It is technical navigation data; normally do not translate identifiers.",
    "LVLN": "Meaning this entry is from a Leveled NPC list. It controls which NPCs can spawn; translate only visible list names if present.",
    "LVLI": "Meaning this entry is from a Leveled Item list. It controls loot or item spawns; translate only visible list names if present.",
    "LVLC": "Meaning this entry is from a Leveled Creature list. It controls creature spawns; translate only visible names if present.",
    "PROJ": "Meaning this entry is from a Projectile record. It is usually technical projectile data; translate only visible projectile names.",
    "ANIO": "Meaning this entry is from an Animated Object record. It is usually technical animation data; translate only player-visible labels.",
    "IDLE": "Meaning this entry is from an Idle Animation record. It is usually technical animation data; translate only visible names.",
    "IDLM": "Meaning this entry is from an Idle Marker record. It is usually technical animation marker data; translate only visible names.",
    "GRAS": "Meaning this entry is from a Grass record. It is usually vegetation rendering data; translate only visible plant names.",
    "TREE": "Meaning this entry is from a Tree record. It usually represents vegetation assets; translate only visible plant/tree names.",
    "KYWD": "Meaning this entry is from a Keyword record. Keywords tag objects, items, locations, or quests for rules and filters; translate only player-facing labels, and keep technical keyword names untouched.",
    "LCTN": "Meaning this entry is from a Location record. It usually contains map/location names, parent location labels, or encounter area names; translate as lore-consistent place names.",
    "LCRT": "Meaning this entry is from a Location Reference Type record. It labels special reference roles inside locations; translate only if visible to players.",
    "AACT": "Meaning this entry is from an Action record. It usually labels animation or gameplay actions and is often technical; translate only visible action labels.",
    "FLOR": "Meaning this entry is from a Flora record. It usually contains names of harvestable plants or interactable natural objects; translate as item/world object names.",
    "HAZD": "Meaning this entry is from a Hazard record. It usually represents damaging areas, traps, or environmental hazards; translate visible names/effect text if present.",
    "SCRL": "Meaning this entry is from a Scroll record. In fantasy games it usually contains scroll item names or descriptions; translate as an item/ability label.",
    "SHOU": "Meaning this entry is from a Shout or special power record. It usually contains ability names and descriptions; translate as a gameplay power.",
    "WOOP": "Meaning this entry is from a Word of Power record. It usually contains special power words or lore terms; preserve canonical names when known.",
    "EQUP": "Meaning this entry is from an Equipment Type record. It usually names an equipment slot/category; translate as a short UI category label.",
    "SCEN": "Meaning this entry is from a Scene record. It organizes dialogue or scripted scenes; translate player-facing scene/dialogue text, not scene identifiers.",
    "DLBR": "Meaning this entry is from a Dialogue Branch record. It groups dialogue topics; translate only player-facing branch/topic labels.",
    "DLVW": "Meaning this entry is from a Dialogue View record. It is usually editor/dialogue structure data; translate only visible labels.",
    "SMBN": "Meaning this entry is from a Story Manager Branch Node. It is usually technical quest/story routing data; translate only visible names.",
    "SMQN": "Meaning this entry is from a Story Manager Quest Node. It is usually technical quest routing data; translate only visible names.",
    "SMEN": "Meaning this entry is from a Story Manager Event Node. It is usually technical event routing data; translate only visible names.",
    "LAND": "Meaning this entry is from a Landscape record. It is terrain data and usually technical; translate only visible location/terrain names.",
    "SCPT": "Meaning this entry is from a Script record. It usually contains script identifiers or legacy script text; preserve identifiers and translate only visible strings.",
    "ECZN": "Meaning this entry is from an Encounter Zone record. It defines encounter/leveling areas and may contain location labels; translate as area names if visible.",
    "SNDR": "Meaning this entry is from a Sound Descriptor record. It is usually technical audio data; translate only visible names.",
    "SNCT": "Meaning this entry is from a Sound Category record. It may appear in settings or audio categories; translate as a concise UI category.",
    "SOPM": "Meaning this entry is from a Sound Output Model record. It is technical audio routing data; translate only visible names.",
    "RFCT": "Meaning this entry is from a Visual Effect record. It is usually technical; translate only visible effect names.",
    "MATO": "Meaning this entry is from a Material Object record. It is usually technical material data; translate only visible names.",
    "OMOD": "Meaning this entry is from an Object Modification record. It usually contains weapon, armor, ship, or item mod names/descriptions; translate as modular equipment UI text.",
    "INNR": "Meaning this entry is from an Instance Naming Rules record. It affects generated item names; translate carefully because it can compose final item names from parts.",
    "PKIN": "Meaning this entry is from a Pack-In record. It usually groups placed objects or prefab-like content; translate only visible names.",
    "RFGP": "Meaning this entry is from a Reference Group record. It groups references and is usually technical; translate only visible labels.",
    "SCCO": "Meaning this entry is from a Scene Collection record. It is usually technical scene organization; translate only visible labels.",
    "STAG": "Meaning this entry is from an Animation Sound Tag Set record. It is technical animation/audio data; translate only visible labels.",
    "AMDL": "Meaning this entry is from an Aim Model record. It is technical aiming/weapon behavior data; translate only visible labels.",
    "PNDT": "Meaning this entry is from a Starfield Planet Data record. It usually describes a planet or planetary metadata; translate as astronomy/location lore text.",
    "STDT": "Meaning this entry is from a Starfield Star Data record. It usually describes a star or star-system data; translate as astronomy/location lore text.",
    "BIOM": "Meaning this entry is from a Starfield Biome record. It usually names or describes a planetary biome; translate as natural environment terminology.",
    "BMMO": "Meaning this entry is from a Starfield Biome Marker record. It usually marks biome-related content and may be technical; translate visible biome labels only.",
    "PCMT": "Meaning this entry is from a Starfield Planet Content Manager Tree record. It is usually procedural content structure; translate visible names only.",
    "PCBN": "Meaning this entry is from a Starfield Planet Content Branch Node record. It is usually procedural content structure; translate visible names only.",
    "PCCN": "Meaning this entry is from a Starfield Planet Content Cell Node record. It is usually procedural content structure; translate visible names only.",
    "SFPT": "Meaning this entry is from a Starfield Surface Pattern record. It may label procedural surface content; translate visible planet/surface labels.",
    "SFTR": "Meaning this entry is from a Starfield Surface Tree record. It is usually procedural world generation data; translate visible labels only.",
    "SFBK": "Meaning this entry is from a Starfield Surface Block record. It is usually procedural world generation data; translate visible labels only.",
    "SFPC": "Meaning this entry is from a Starfield Surface Pattern Config record. It is usually procedural world generation data; translate visible labels only.",
    "RSGD": "Meaning this entry is from a Starfield Resource Generation Data record. It may name resources or generation rules; preserve resource codes and translate visible resource labels.",
    "IRES": "Meaning this entry is from a Starfield Instance/Resource record. It often relates to resources, research, or crafting data; translate visible names and preserve identifiers.",
    "RSPJ": "Meaning this entry is from a Starfield Research Project record. It usually contains research project names or descriptions; translate as research/crafting UI text.",
    "SPCH": "Meaning this entry is from a Starfield Speech Challenge record. It usually contains persuasion challenge text; translate as dialogue/gameplay prompt text.",
    "TMLM": "Meaning this entry is from a Starfield Terminal Menu record. It usually contains terminal menu entries or terminal page labels; translate as terminal UI text.",
    "GBFM": "Meaning this entry is from a Starfield Generic Base Form record. It can hold generalized object, quest, or mission-board text; use EDID and field context to decide whether it is item, quest, or UI text.",
    "GBFT": "Meaning this entry is from a Starfield Generic Base Form Template record. It usually provides template text for generated content; preserve placeholders and translate generic labels consistently.",
    "LVLB": "Meaning this entry is from a Starfield Leveled Base Form record. It usually controls generated/spawned forms; translate visible labels only.",
    "LVSC": "Meaning this entry is from a Starfield Leveled Space Cell record. It usually controls generated space cells; translate visible labels only.",
    "AFFE": "Meaning this entry is from a Starfield Affinity Event record. It may contain companion affinity or relationship event text; translate as character/relationship context.",
    "FXPD": "Meaning this entry is from a Starfield Facial Expression Data record. It is usually technical face animation data; translate visible labels only.",
    "TRAV": "Meaning this entry is from a Starfield Traversal record. It usually describes movement/traversal behavior and is technical; translate visible labels only.",
    "WBAR": "Meaning this entry is from a Starfield Weapon Barrel Model record. It may name weapon barrel parts; translate as weapon-part UI text and preserve model codes.",
    "WWED": "Meaning this entry is from a Wwise Event record. It is audio event data; preserve event identifiers and translate only visible labels.",
    "WKMF": "Meaning this entry is from a Wwise Keyword Mapping record. It is technical audio mapping data; translate only visible labels.",
    "GPOF": "Meaning this entry is from a Game Option record. It usually appears as a settings option; translate as concise settings UI text.",
    "GPOG": "Meaning this entry is from a Game Option Group record. It usually appears as a settings category; translate as concise settings UI text.",
    "TODD": "Meaning this entry is from Time of Day Data. It is usually technical environment data; translate visible labels only.",
    "PCRD": "Meaning this entry is from a Fallout 76 Perk Card record. It usually contains perk card names and descriptions; translate as gameplay card UI.",
    "PPAK": "Meaning this entry is from a Fallout 76 Perk Card Pack record. It usually contains perk pack names or reward text; translate as reward UI.",
    "LVPC": "Meaning this entry is from a Fallout 76 Leveled Perk Card record. It controls perk card rewards; translate visible labels only.",
    "PACH": "Meaning this entry is from a Fallout 76 Power Armor Chassis record. It usually names power armor chassis data; translate as equipment text.",
    "EMOT": "Meaning this entry is from a Fallout 76 Emote record. It usually contains emote names or descriptions; translate as short social UI text.",
    "ECAT": "Meaning this entry is from a Fallout 76 Emote Category record. It usually names emote menu categories; translate as concise UI text.",
    "AVTR": "Meaning this entry is from a Fallout 76 Avatar record. It usually names player avatar icons; translate as profile UI text.",
    "CNCY": "Meaning this entry is from a Currency record. It usually names a currency or token; preserve abbreviations and translate player-facing names.",
    "WAVE": "Meaning this entry is from a Fallout 76 Wave Encounter record. It may describe encounter waves; translate visible event text only.",
    "PLYT": "Meaning this entry is from a Player Title record. It usually contains player title labels; translate as short profile/title text.",
    "QMDL": "Meaning this entry is from a Fallout 76 Quest Module record. It may contain modular quest text; translate as quest UI context.",
    "FISH": "Meaning this entry is from a Fish record. It usually contains fish names or fishing-related item text; translate as creature/item names.",
    "UTIL": "Meaning this entry is from a Utility record. It is often technical; translate only visible labels.",
    "GMRW": "Meaning this entry is from a Game Reward record. It usually contains reward names or descriptions; translate as reward UI text.",
    "CREA": "Meaning this entry is from a Fallout 3/New Vegas Creature record. It usually contains creature names or descriptions; translate as creature/NPC names.",
    "ACRE": "Meaning this entry is from a placed Creature reference. It identifies a placed creature; translate only visible names.",
    "IMOD": "Meaning this entry is from a Fallout New Vegas Item Mod record. It usually contains weapon/item modification names; translate as equipment mod UI text.",
    "REPU": "Meaning this entry is from a Fallout New Vegas Reputation record. It usually contains faction/location reputation names and descriptions; translate as reputation UI text.",
    "RCCT": "Meaning this entry is from a Fallout New Vegas Recipe Category record. It usually names crafting recipe categories; translate as crafting UI text.",
    "RCPE": "Meaning this entry is from a Fallout New Vegas Recipe record. It usually contains recipe names and descriptions; translate as crafting UI text.",
    "DEHY": "Meaning this entry is from a Fallout New Vegas Dehydration Stage record. It usually contains survival status text; translate as gameplay status UI.",
    "HUNG": "Meaning this entry is from a Fallout New Vegas Hunger Stage record. It usually contains survival status text; translate as gameplay status UI.",
    "SLPD": "Meaning this entry is from a Fallout New Vegas Sleep Deprivation Stage record. It usually contains survival status text; translate as gameplay status UI.",
    "LSCT": "Meaning this entry is from a Fallout New Vegas Loading Screen Type record. It usually categorizes loading screens; translate visible labels only.",
}


def signature_explanation(signature: str) -> str:
    """Return a concise explanation for one four-character record signature."""

    normalized = str(signature or "").upper()
    return DETAILED_SIGNATURE_EXPLANATIONS.get(
        normalized,
        (
            "Meaning this entry is from an uncommon or currently unmapped Bethesda plugin record type. "
            "Use EDID, signature, field, and source text to infer whether it is UI text, item text, dialogue, quest text, or technical data; preserve identifiers and placeholders."
        ),
    )


def render_signature_context(signatures: Iterable[str]) -> str:
    """Render only the explanations needed by the current batch."""

    normalized = sorted({str(signature or "").upper() for signature in signatures if str(signature or "").strip()})
    if not normalized:
        return ""
    return "\n".join(f"- {signature}: {signature_explanation(signature)}" for signature in normalized)


__all__ = [
    "DETAILED_SIGNATURE_EXPLANATIONS",
    "SIGNATURE_EXPLANATIONS",
    "render_signature_context",
    "signature_explanation",
]
