/**
 * C.3.1 - C.3.4 acceptance carryforward: content-hash lease violation harness.
 *
 * Carryforward source:
 *   .opencode/artifacts/mo2-mcp/e2e-test-plan/run-20260617T002922Z/CURRENT-STATE.md
 *
 * The C.3 acceptance run never produced real verdicts for these because fixer-beta
 * couldn't reach the apply path with confidence in the live MCP. This file closes
 * the test gap by exercising the same four contract points against the routeable
 * plan/apply pipeline (runPlanMode + runApplyMode) with a realistic
 * modlist.txt-shaped fixture and assertions on the drift shape.
 *
 * Contract points exercised (per task spec):
 *   C.3.1 - external touch (append) -> lease_violation, drift hash mismatch
 *   C.3.2 - external full-rewrite   -> lease_violation, drift hash + size mismatch
 *   C.3.3 - second apply on same plan_id+lease_token (one-shot semantics)
 *           -> plan_expired_or_unknown
 *   C.3.4 - plan TTL expiration before apply
 *           -> plan_expired_or_unknown
 *
 * Note on prior coverage:
 *   - `tests/plan-apply.test.ts` already has unit-level coverage of a basic
 *     "file mutated between plan and apply -> lease_violation" round-trip and
 *     a PlanCache TTL test. These tests are additive: they use realistic
 *     modlist.txt fixtures and assert on the drift shape (paths, hash diff,
 *     size diff) and the one-shot semantics that the existing tests don't
 *     explicitly cover.
 *   - `tests/lease.test.ts` covers the lower-level fingerprintFile + verifyLease
 *     primitives.
 */
import { describe, it, expect } from "vitest";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  PlanCache,
  runPlanMode,
  runApplyMode,
  type PlanApplyHandler,
} from "../src/plan-apply.js";
import { SnapshotManager } from "../src/snapshot.js";
import { AuditLogger } from "../src/audit.js";
import type { ToolContext } from "../src/types.js";
import type { LeaseDrift } from "../src/lease.js";

/**
 * Realistic modlist.txt-shaped fixture content. MO2 mod list format:
 *   '+' prefix = enabled, '-' prefix = disabled, one mod per line.
 * Used by C.3.1/C.3.2 so external mutations look like the kind of changes
 * an external editor or another MO2 instance would actually make.
 */
const SAMPLE_MODLIST =
  "# This file was automatically generated by Mod Organizer.\n" +
  "+UnofficialFalloutPatch\n" +
  "+ArmorKeywords\n" +
  "+CommonwealthCuts\n" +
  "-DisabledExample\n";

interface LeaseTestEnv {
  root: string;
  target: string;
  cache: PlanCache;
  snaps: SnapshotManager;
  ctx: ToolContext;
}

/**
 * Setup helper: spin up a fresh tmp mo2Root, write a modlist.txt-shaped
 * target, and return a PlanCache + SnapshotManager + ToolContext stub wired
 * to that root. Each test gets its own root so lease-lock files under
 * <root>/.mo2-mcp/leases/ never collide between tests.
 */
async function setupLeaseTest(
  modlistContent: string = SAMPLE_MODLIST,
): Promise<LeaseTestEnv> {
  const root = await mkdtemp(join(tmpdir(), "lease-violation-"));
  const target = join(root, "modlist.txt");
  await writeFile(target, modlistContent, "utf8");

  const cache = new PlanCache();
  const snaps = new SnapshotManager(join(root, ".mo2-mcp", "snapshots"), "sess-c3");
  const audit = new AuditLogger(join(root, ".mo2-mcp", "audit"), "sess-c3");

  const ctx = {
    config: {
      mo2Root: root,
      permissionCeiling: "metadata-editable" as const,
      allowedProfiles: ["Default"],
      deny: [],
      snapshotRoot: join(root, ".mo2-mcp", "snapshots"),
      auditRoot: join(root, ".mo2-mcp", "audit"),
    },
    sessionId: "sess-c3",
    plans: cache,
    snapshots: snaps,
    audit,
  } satisfies ToolContext;

  return { root, target, cache, snaps, ctx };
}

/**
 * Synthetic handler that mirrors a real T3 mutation:
 * buildPlan registers the modlist file as a text-file lease target;
 * applyMutation flips the first '+' line to '-' (semantically: toggle off
 * the first enabled mod). The mutation only runs if the lease holds.
 */
function makeModlistToggleHandler(target: string): PlanApplyHandler {
  return {
    toolName: "test_c3_modlist_toggle",
    async buildPlan() {
      return {
        diff: "toggle first enabled mod off",
        affectedFiles: [target],
        targets: [{ path: target, kind: "text-file" }],
      };
    },
    async applyMutation() {
      const current = await readFile(target, "utf8");
      const mutated = current.replace(/^\+/m, "-");
      await writeFile(target, mutated, "utf8");
      return { mutated: true };
    },
  };
}

describe("C.3.x lease violation harness", () => {
  it("C.3.1: external touch (append) invalidates the lease (lease_violation)", async () => {
    const { target, cache, snaps, ctx } = await setupLeaseTest();
    const handler = makeModlistToggleHandler(target);

    const plan = await runPlanMode(handler, { mode: "plan" }, ctx, cache, snaps);
    expect(plan.ok).toBe(true);
    if (!plan.ok) throw new Error(plan.error.message);
    const { planId, lease_token } = plan.result;

    // External mutation: append a single line. Different content, different
    // size, different SHA-256 -> drift expected.
    const externalContent = SAMPLE_MODLIST + "+ExternalAddition\n";
    await writeFile(target, externalContent, "utf8");

    const apply = await runApplyMode(
      handler,
      { plan_id: planId, lease_token },
      ctx,
      cache,
      snaps,
    );

    expect(apply.ok).toBe(false);
    if (!apply.ok) {
      expect(apply.error.code).toBe("lease_violation");
      expect(apply.error.message).toMatch(/changed since plan/i);
      const drift = apply.error.drift as LeaseDrift[];
      expect(drift).toHaveLength(1);
      expect(drift[0].path).toBe(target);
      expect(drift[0].planComponent.kind).toBe("text-file");
      expect(drift[0].currentComponent.kind).toBe("text-file");
      expect(drift[0].planComponent.contentHash).not.toBe(
        drift[0].currentComponent.contentHash,
      );
    }

    // External write is preserved (not rolled back, not double-mutated)
    expect(await readFile(target, "utf8")).toBe(externalContent);
  });

  it("C.3.2: external full-rewrite invalidates the lease (lease_violation + size diff)", async () => {
    const { target, cache, snaps, ctx } = await setupLeaseTest();
    const handler = makeModlistToggleHandler(target);

    const plan = await runPlanMode(handler, { mode: "plan" }, ctx, cache, snaps);
    expect(plan.ok).toBe(true);
    if (!plan.ok) throw new Error(plan.error.message);
    const { planId, lease_token } = plan.result;

    // External full rewrite: entirely different content + a very different size.
    // Picked to be much shorter than SAMPLE_MODLIST so the size delta is unambiguous.
    const rewritten = "# overwritten by an external editor\n+OnlyOneMod\n";
    expect(rewritten.length).not.toBe(SAMPLE_MODLIST.length);
    await writeFile(target, rewritten, "utf8");

    const apply = await runApplyMode(
      handler,
      { plan_id: planId, lease_token },
      ctx,
      cache,
      snaps,
    );

    expect(apply.ok).toBe(false);
    if (!apply.ok) {
      expect(apply.error.code).toBe("lease_violation");
      const drift = apply.error.drift as LeaseDrift[];
      expect(drift).toHaveLength(1);
      expect(drift[0].path).toBe(target);
      // Both hash AND size differ on a full rewrite of different length.
      expect(drift[0].planComponent.contentHash).not.toBe(
        drift[0].currentComponent.contentHash,
      );
      expect(drift[0].planComponent.size).not.toBe(
        drift[0].currentComponent.size,
      );
      expect(drift[0].currentComponent.size).toBe(rewritten.length);
    }

    // Confirm the external write survived (handler did not run, nothing rolled back)
    expect(await readFile(target, "utf8")).toBe(rewritten);
  });

  it("C.3.3: second apply on a consumed lease rejects (plan_expired_or_unknown)", async () => {
    const { target, cache, snaps, ctx } = await setupLeaseTest();
    const handler = makeModlistToggleHandler(target);

    const plan = await runPlanMode(handler, { mode: "plan" }, ctx, cache, snaps);
    expect(plan.ok).toBe(true);
    if (!plan.ok) throw new Error(plan.error.message);
    const { planId, lease_token } = plan.result;

    // First apply succeeds and mutates the file.
    const apply1 = await runApplyMode(
      handler,
      { plan_id: planId, lease_token },
      ctx,
      cache,
      snaps,
    );
    expect(apply1.ok).toBe(true);
    // Sanity: the handler ran (first '+' became '-')
    const afterFirst = await readFile(target, "utf8");
    expect(afterFirst).toContain("-UnofficialFalloutPatch");
    expect(afterFirst).not.toContain("+UnofficialFalloutPatch");

    // PlanCache.consume() is one-shot: it deletes the plan record.
    // Re-applying with the SAME plan_id + lease_token must reject.
    const apply2 = await runApplyMode(
      handler,
      { plan_id: planId, lease_token },
      ctx,
      cache,
      snaps,
    );
    expect(apply2.ok).toBe(false);
    if (!apply2.ok) {
      expect(apply2.error.code).toBe("plan_expired_or_unknown");
      expect(apply2.error.message).toMatch(/not found|expired/i);
    }

    // File content should NOT have been mutated a second time (apply2 short-circuited)
    expect(await readFile(target, "utf8")).toBe(afterFirst);
  });

  it("C.3.4: expired plan rejects (plan_expired_or_unknown)", async () => {
    const { target, cache, snaps, ctx } = await setupLeaseTest();
    const handler = makeModlistToggleHandler(target);

    const plan = await runPlanMode(handler, { mode: "plan" }, ctx, cache, snaps);
    expect(plan.ok).toBe(true);
    if (!plan.ok) throw new Error(plan.error.message);
    const { planId, lease_token } = plan.result;

    // Force expiration by re-storing the same plan record with a past
    // expiresAt. PlanCache.store() supports both planId and expiresAt
    // overrides for exactly this kind of deterministic TTL test, so we
    // don't need to mock the clock or wait wall-clock time.
    const original = cache.get(planId);
    expect(original).not.toBeNull();
    if (!original) throw new Error("expected cached plan to exist pre-expiration");
    cache.store({
      planId: original.planId,
      expiresAt: Date.now() - 1, // already in the past
      tool: original.tool,
      args: original.args,
      diff: original.diff,
      affectedFiles: original.affectedFiles,
      lease: original.lease,
      leaseLockTargetHashes: original.leaseLockTargetHashes,
    });

    const apply = await runApplyMode(
      handler,
      { plan_id: planId, lease_token },
      ctx,
      cache,
      snaps,
    );

    expect(apply.ok).toBe(false);
    if (!apply.ok) {
      expect(apply.error.code).toBe("plan_expired_or_unknown");
      expect(apply.error.message).toMatch(/not found|expired/i);
    }

    // File untouched (handler never ran)
    expect(await readFile(target, "utf8")).toBe(SAMPLE_MODLIST);
  });
});
